name: Build & Push Docker Image

on:
  push:
    branches:
      - portfolio-3

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}


      - name: Deploy to OCI
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_KEY }}
          script: |
            curl -fsSL \
            https://gist.githubusercontent.com/samay15jan/296498459d1607226b8a59d4ae7b3385/raw/blue-green_deploy.sh \
            -o blue-green_deploy.sh
            chmod +x blue-green_deploy.sh
            ./blue-green_deploy.sh
            rm blue-green_deploy.sh
